version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: server_dashboard_backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - dashboard_network

  frontend:
    build:
      context: ./frontend
    container_name: server_dashboard_frontend
    ports:
      - "3000:80"
    networks:
      - dashboard_network
    depends_on:
      - backend

networks:
  dashboard_network:
    driver: bridge
